services:
  liquibase:
    build:
      context: .
      dockerfile: Dockerfile # ระบุ Dockerfile ที่สร้างขึ้นเอง
    volumes:
      - ./changelog:/liquibase/changelog # Mapping โฟลเดอร์ changelog
      - ./changelog/liquibase.docker.properties:/liquibase/liquibase.docker.properties # Mapping ไฟล์ properties
    command: --defaults-file=/liquibase/liquibase.docker.properties update
    # depends_on:
    #   - postgres
    networks:
      - poc-liquibase-destination

networks:
  poc-liquibase-destination:
    external: true
